FROM spark-base-graalvm-devel:latest

COPY start-master.sh /

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /spark/logs

EXPOSE 7077 6066 8080

CMD ["/bin/bash", "/start-master.sh"]
