version: "3.7"
services:
  spark-master:
    image: spark-master-graalvm:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: spark-worker-graalvm:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "9091:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  spark-worker-2:
    image: spark-worker-graalvm:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "9092:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
